<?php
namespace App\Services;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Http;
class CollabSourceService
{
    public static function snapshot(): array
    {
        $raw=null; if(Storage::disk('local')->exists('collab_achievement.json'))$raw=json_decode(Storage::disk('local')->get('collab_achievement.json'),true); if(!is_array($raw)){ $path=base_path('../regionalb.online/public_html/runtime/cache/collab_achievement.json'); $raw=is_file($path)?json_decode((string)file_get_contents($path),true):[]; }
        $reports=[]; foreach(($raw['reports']??[]) as $name=>$report){$rows=$report['tables'][0]??[];$rows=is_array($rows)?$rows:[];$columns=0;foreach($rows as $row)if(is_array($row))$columns=max($columns,count($row));$reports[$name]=['name'=>$name,'rows'=>$rows,'row_count'=>count($rows),'column_count'=>$columns,'source_url'=>$report['source_url']??'','source_mode'=>$report['source_mode']??'','cached_at'=>$report['cached_at']??'','created_at'=>$report['created_at']??'','error'=>$report['error']??''];} return ['synced_at'=>$raw['synced_at']??'','reports'=>$reports,'errors'=>$raw['errors']??[]];
    }
    public static function sync(): array { $urls=['Closing Collab'=>'https://cb.web.id/pencapaian_closing_collab_template.php','Herreg Collab'=>'https://cb.web.id/pencapaian_herreg_collab_template.php','Closing Kampus Regional'=>'https://cb.web.id/pencapaian_closing_perkampus_peregional.php','Herreg Kampus Regional'=>'https://cb.web.id/pencapaian_closing_herreg_perkampus_peregional.php','Closing Personal Per Regional'=>'https://cb.web.id/pencapaian_closing_personal_per_regional.php','Rekapitulasi PMB Periode Prioritas P2K'=>'https://cb.web.id/rekapitulasi_pencapaian_pmb_periode_prioritas.php?program=p2k']; $reports=[];$errors=[];foreach($urls as $name=>$url){try{$html=Http::timeout(20)->withHeaders(['User-Agent'=>'RegionalB-Laravel/1.0'])->get($url)->body();preg_match_all('/<table[^>]*>(.*?)<\/table>/is',$html,$tables);$rows=[];foreach(array_slice($tables[1]??[],0,1) as $table){preg_match_all('/<tr[^>]*>(.*?)<\/tr>/is',$table,$trs);foreach($trs[1]??[] as $tr){preg_match_all('/<t[dh][^>]*>(.*?)<\/t[dh]>/is',$tr,$cells);$row=[];foreach($cells[1]??[] as $cell)$row[]=trim(html_entity_decode(strip_tags($cell),ENT_QUOTES|ENT_HTML5,'UTF-8'));if($row!==[])$rows[]=$row;}}if($rows===[])throw new \RuntimeException('Tabel tidak ditemukan');$reports[$name]=['name'=>$name,'tables'=>[$rows],'source_url'=>$url,'source_mode'=>'live_api','cached_at'=>now()->format('Y-m-d H:i:s')];}catch(\Throwable $e){$errors[$name]=$e->getMessage();}}$result=['synced_at'=>now()->format('Y-m-d H:i:s'),'reports'=>$reports,'errors'=>$errors];if($reports!==[]){Storage::disk('local')->put('collab_achievement.json',json_encode($result,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT));}else{$path=base_path('../regionalb.online/public_html/runtime/cache/collab_achievement.json');if(is_file($path))Storage::disk('local')->put('collab_achievement.json',(string)file_get_contents($path));}return self::snapshot(); }
}
