@php use App\Models\RsmUser; use App\Support\RsmRole; @endphp
<x-layouts.app title="Kelola User" active="users">
    @if(session('status'))<div class="mb-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{{ session('status') }}</div>@endif @if($errors->any())<div class="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
    <section class="rounded-2xl glass-card p-5"><h2 class="text-base font-semibold text-ink">Tambah User RSM</h2><form method="POST" action="{{ route('users.store') }}" class="mt-4 grid gap-3 md:grid-cols-3">@csrf
        <input name="name" placeholder="Nama" required class="rounded-lg border-border bg-surface-muted"><input name="nik" placeholder="NIK (opsional)" class="rounded-lg border-border bg-surface-muted"><input name="username" placeholder="Username" required class="rounded-lg border-border bg-surface-muted"><select name="user_role" class="rounded-lg border-border bg-surface-muted">@foreach(RsmUser::ROLES as $role)<option value="{{ $role }}">{{ RsmRole::label($role) }}</option>@endforeach</select><select name="area" class="rounded-lg border-border bg-surface-muted"><option>Regional B</option><option>Regional A</option></select><select name="regional" class="rounded-lg border-border bg-surface-muted"><option value="">Pilih regional</option>@foreach($regionals as $regional)<option>{{ $regional }}</option>@endforeach</select><select name="campus_name" class="rounded-lg border-border bg-surface-muted"><option value="">Pilih kampus/unit (opsional)</option>@foreach($campuses as $campus)<option>{{ $campus }}</option>@endforeach</select><input name="new_user_password" value="kptsukses" minlength="6" required class="rounded-lg border-border bg-surface-muted"><div class="flex items-center"><button class="rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white">Tambah User</button></div>
    </form></section>
    <section class="mt-5 overflow-x-auto rounded-2xl glass-card p-5"><h2 class="mb-3 text-base font-semibold text-ink">Daftar User RSM</h2><table class="w-full min-w-[1150px] text-left text-sm"><thead><tr class="border-b border-border text-xs text-ink-muted"><th class="py-2 pr-3">Nama</th><th class="py-2 pr-3">Username</th><th class="py-2 pr-3">Role</th><th class="py-2 pr-3">Area/Regional</th><th class="py-2 pr-3">Status</th><th class="py-2">Aksi</th></tr></thead><tbody>@foreach($users as $managedUser)<tr class="border-b border-border/60 align-top"><td class="py-2 pr-3">{{ $managedUser->name }}</td><td class="py-2 pr-3">{{ $managedUser->username }}</td><td class="py-2 pr-3">{{ RsmRole::label($managedUser->role) }}</td><td class="py-2 pr-3">{{ $managedUser->area ?: '-' }} / {{ $managedUser->regional ?: '-' }}</td><td class="py-2 pr-3">{{ $managedUser->is_active ? 'Aktif' : 'Nonaktif' }}</td><td class="py-2"><div class="flex flex-wrap items-center gap-1.5"><div x-data="{ open: false }">
    <button type="button" @click="open = true" title="Edit" aria-label="Edit" class="rounded-md border border-border p-1.5 text-ink-muted hover:text-ink"><x-icon name="edit" class="h-3.5 w-3.5" /></button>
    <div x-show="open" x-cloak @keydown.escape.window="open = false" class="fixed inset-0 z-40 flex items-center justify-center p-4" style="background: rgba(15,23,42,0.45)">
        <div @click.outside="open = false" class="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl border border-border bg-surface p-5 shadow-2xl">
            <div class="mb-4 flex items-center justify-between gap-3">
                <h3 class="text-base font-semibold text-ink">Edit {{ $managedUser->name }}</h3>
                <button type="button" @click="open = false" aria-label="Tutup" class="rounded-lg border border-border p-1.5 text-ink-muted hover:text-ink"><x-icon name="close" class="h-4 w-4" /></button>
            </div>
            <form method="POST" action="{{ route('users.update',$managedUser) }}" class="grid gap-3 sm:grid-cols-2">
                @csrf @method('PATCH')
                <label class="grid gap-1 text-xs text-ink-muted sm:col-span-2">Nama<input name="name" value="{{ $managedUser->name }}" required class="rounded-lg border-border bg-surface-muted"></label>
                <label class="grid gap-1 text-xs text-ink-muted">Role<select name="user_role" class="rounded-lg border-border bg-surface-muted">@foreach(RsmUser::ROLES as $role)<option value="{{ $role }}" @selected($managedUser->role===$role)>{{ RsmRole::label($role) }}</option>@endforeach</select></label>
                <label class="grid gap-1 text-xs text-ink-muted">Regional<select name="regional" class="rounded-lg border-border bg-surface-muted"><option value="">Pilih regional</option>@if($managedUser->regional && !in_array($managedUser->regional,$regionals,true))<option value="{{ $managedUser->regional }}" selected>{{ $managedUser->regional }}</option>@endif @foreach($regionals as $regional)<option @selected($managedUser->regional===$regional)>{{ $regional }}</option>@endforeach</select></label>
                <label class="grid gap-1 text-xs text-ink-muted sm:col-span-2">Kampus/Unit<select name="campus_name" class="rounded-lg border-border bg-surface-muted"><option value="">Pilih kampus/unit</option>@if($managedUser->campus_name && !in_array($managedUser->campus_name,$campuses,true))<option value="{{ $managedUser->campus_name }}" selected>{{ $managedUser->campus_name }}</option>@endif @foreach($campuses as $campus)<option @selected($managedUser->campus_name===$campus)>{{ $campus }}</option>@endforeach</select></label>
                <label class="grid gap-1 text-xs text-ink-muted sm:col-span-2">No. HP<input name="phone_number" value="{{ $managedUser->phone_number }}" class="rounded-lg border-border bg-surface-muted"></label>
                <label class="grid gap-1 text-xs text-ink-muted sm:col-span-2">Bio<textarea name="bio_text" rows="2" class="rounded-lg border-border bg-surface-muted">{{ $managedUser->bio_text }}</textarea></label>
                <div class="flex justify-end gap-2 sm:col-span-2">
                    <button type="button" @click="open = false" class="rounded-lg border border-border px-3 py-2 text-sm">Batal</button>
                    <button class="rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white">Simpan edit</button>
                </div>
            </form>
        </div>
    </div>
</div><form method="POST" action="{{ route('users.toggle',$managedUser) }}">@csrf<button title="{{ $managedUser->is_active ? 'Nonaktifkan' : 'Aktifkan' }}" aria-label="{{ $managedUser->is_active ? 'Nonaktifkan' : 'Aktifkan' }}" class="rounded-md border p-1.5 {{ $managedUser->is_active ? 'border-tone-amber text-tone-amber' : 'border-tone-green text-tone-green' }}"><x-icon name="ban" class="h-3.5 w-3.5" /></button></form>@if($managedUser->id !== auth()->id())<form method="POST" action="{{ route('users.reset-password',$managedUser) }}" class="flex items-center gap-1">@csrf<input name="new_password" minlength="6" placeholder="Password baru" class="w-24 rounded-md border border-border px-1.5 py-1 text-xs"><button title="Reset password" aria-label="Reset password" class="rounded-md border border-border p-1.5 text-ink-muted hover:text-ink"><x-icon name="lock" class="h-3.5 w-3.5" /></button></form><form method="POST" action="{{ route('users.destroy',$managedUser) }}" onsubmit="return confirm('Hapus user ini?')">@csrf @method('DELETE')<button title="Hapus" aria-label="Hapus" class="rounded-md border border-tone-red p-1.5 text-tone-red"><x-icon name="trash" class="h-3.5 w-3.5" /></button></form>@endif</div></td></tr>@endforeach</tbody></table></section>
</x-layouts.app>
