<x-layouts.app title="Target Bulanan" active="targets">
    @if (session('status'))<div class="mb-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{{ session('status') }}</div>@endif
    @if ($errors->any())<div class="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
    <section class="rounded-2xl glass-card p-5"><h2 class="text-base font-semibold text-ink">Atur Target Bulanan</h2>
        <form method="POST" action="{{ route('targets.store') }}" class="mt-4 grid gap-3 md:grid-cols-3">@csrf
            <label class="grid gap-1 text-xs text-ink-muted">Bulan target<input type="month" name="target_month" value="{{ old('target_month', now()->format('Y-m')) }}" required class="rounded-lg border-border bg-surface-muted"></label>
            <label class="grid gap-1 text-xs text-ink-muted">Scope<select name="scope_type" class="rounded-lg border-border bg-surface-muted">@foreach(['regional'=>'Regional','wilayah'=>'Wilayah','unit'=>'Unit/Kampus','staff'=>'Staff'] as $key=>$label)<option value="{{ $key }}" @selected(old('scope_type','staff')===$key)>{{ $label }}</option>@endforeach</select></label>
            <label class="flex items-center gap-2 self-end text-sm text-ink"><input type="checkbox" name="apply_all_scope" value="1" @checked(old('apply_all_scope'))> Terapkan ke semua pilihan scope</label>
            <label class="grid gap-1 text-xs text-ink-muted">Wilayah<select name="wilayah" class="rounded-lg border-border bg-surface-muted"><option value="">Pilih wilayah</option>@foreach($references['regionals'] as $value)<option @selected(old('wilayah')===$value)>{{ $value }}</option>@endforeach</select></label>
            <label class="grid gap-1 text-xs text-ink-muted">Unit/Kampus<select name="unit_name" class="rounded-lg border-border bg-surface-muted"><option value="">Pilih unit</option>@foreach($references['campuses'] as $value)<option @selected(old('unit_name')===$value)>{{ $value }}</option>@endforeach</select></label>
            <label class="grid gap-1 text-xs text-ink-muted">Staff<select name="staff_name" class="rounded-lg border-border bg-surface-muted"><option value="">Pilih staff</option>@foreach($references['staff'] as $row)<option @selected(old('staff_name')===$row->name)>{{ $row->name }}</option>@endforeach</select></label>
            @foreach(['target_leads'=>'Target Leads','target_follow_up'=>'Target Follow Up','target_registrasi'=>'Target Registrasi','target_herregistrasi'=>'Target Herregistrasi','target_anggaran'=>'Target Anggaran'] as $field=>$label)<label class="grid gap-1 text-xs text-ink-muted">{{ $label }}<input type="number" min="0" step="{{ $field === 'target_anggaran' ? '0.01' : '1' }}" name="{{ $field }}" value="{{ old($field, 0) }}" class="rounded-lg border-border bg-surface-muted"></label>@endforeach
            <label class="grid gap-1 text-xs text-ink-muted md:col-span-2">Catatan<textarea name="notes" rows="2" class="rounded-lg border-border bg-surface-muted">{{ old('notes') }}</textarea></label><div class="flex items-end"><button class="rounded-lg bg-brand-600 px-4 py-2 text-sm font-semibold text-white">Simpan target</button></div>
        </form>
    </section>
    <section class="mt-5 overflow-x-auto rounded-2xl glass-card p-5"><h2 class="mb-3 text-base font-semibold text-ink">Target staff terbaru</h2><table class="w-full min-w-[950px] text-left text-sm"><thead><tr class="border-b border-border text-xs text-ink-muted"><th class="py-2 pr-3">Bulan</th><th class="py-2 pr-3">Wilayah</th><th class="py-2 pr-3">Unit</th><th class="py-2 pr-3">Staff</th><th class="py-2 pr-3">Leads</th><th class="py-2 pr-3">Registrasi</th><th class="py-2 pr-3">Herregistrasi</th><th class="py-2">Anggaran</th></tr></thead><tbody>@forelse($targets as $target)<tr class="border-b border-border/60"><td class="py-2 pr-3">{{ $target->target_month }}</td><td class="py-2 pr-3">{{ $target->wilayah ?: '-' }}</td><td class="py-2 pr-3">{{ $target->unit_name ?: '-' }}</td><td class="py-2 pr-3">{{ $target->staff_name ?: '-' }}</td><td class="py-2 pr-3">{{ $target->target_leads }}</td><td class="py-2 pr-3">{{ $target->target_registrasi }}</td><td class="py-2 pr-3">{{ $target->target_herregistrasi }}</td><td class="py-2">Rp {{ number_format((float) $target->target_anggaran,0,',','.') }}</td></tr>@empty<tr><td colspan="8" class="py-8 text-center text-ink-muted">Belum ada target staff.</td></tr>@endforelse</tbody></table></section>
</x-layouts.app>
