<x-layouts.app title="Profil Saya" active="profile">
    <div class="rounded-3xl bg-[#101227] p-4 text-white shadow-2xl sm:p-6">
        <div class="grid gap-5 lg:grid-cols-[270px_1fr]">
            <aside class="rounded-2xl border border-white/10 bg-[#212446] p-5 text-center">
                <div class="mx-auto flex h-40 w-40 items-center justify-center overflow-hidden rounded-2xl border-2 border-white/60 bg-gradient-to-br from-emerald-400 to-sky-400 text-4xl font-black shadow-xl">
                    @if($user->photo_path)<img src="{{ $user->photoUrl() }}" alt="{{ $user->name }}" class="h-full w-full object-cover">@else{{ strtoupper(mb_substr($user->name ?: 'U',0,1)) }}@endif
                </div>
                <h2 class="mt-4 text-lg font-bold">{{ $user->name }}</h2>
                <p class="text-xs text-indigo-200">{{ $user->username }}</p>
                <div class="mt-3 flex flex-wrap justify-center gap-x-2 text-xs font-semibold text-indigo-100"><span>{{ $user->jabatan ?: \App\Support\RsmRole::label($user->role) }}</span><span>•</span><span>{{ $user->regional ?: 'Wilayah belum diatur' }}</span></div>
                <div class="mt-5 rounded-2xl bg-[#090b1e]/60 p-4 text-left"><div class="flex justify-between text-xs text-indigo-200"><span>Level {{ $level }}</span><strong class="text-white">{{ number_format($xp,0,',','.') }} XP</strong></div><div class="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div class="h-full rounded-full bg-gradient-to-r from-emerald-400 to-sky-400" style="width:{{ $levelProgress }}%"></div></div><p class="mt-2 text-xs text-indigo-200">League {{ $league }}</p></div>
                <nav class="mt-5 grid gap-1 text-left text-sm font-semibold text-indigo-100"><a href="#ringkasan" class="rounded-xl bg-black/25 px-3 py-2">Ringkasan</a><a href="#pencapaian" class="rounded-xl px-3 py-2 hover:bg-black/25">Pencapaian</a><a href="#aktivitas" class="rounded-xl px-3 py-2 hover:bg-black/25">Aktivitas</a><a href="#pengaturan" class="rounded-xl px-3 py-2 hover:bg-black/25">Pengaturan Profil</a></nav>
            </aside>
            <div class="space-y-5">
                <section id="ringkasan" class="grid gap-3 sm:grid-cols-3"><article class="rounded-2xl border border-white/10 bg-[#35385f] p-4"><span class="text-xs text-indigo-200">League</span><strong class="mt-2 block text-xl">{{ $league }}</strong><small class="text-indigo-200">XP dan konsistensi</small></article><article class="rounded-2xl border border-white/10 bg-[#35385f] p-4"><span class="text-xs text-indigo-200">Aktivitas</span><strong class="mt-2 block text-xl">{{ number_format($stats['reports'],0,',','.') }}</strong><small class="text-indigo-200">Total kegiatan</small></article><article class="rounded-2xl border border-white/10 bg-[#35385f] p-4"><span class="text-xs text-indigo-200">Aura</span><strong class="mt-2 block text-xl">{{ $score }}/100</strong><small class="text-indigo-200">Skor performa</small></article></section>
                <section class="rounded-2xl border border-white/10 bg-[#35385f] p-5"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-widest text-sky-300">Profil User</p><h2 class="mt-1 text-2xl font-bold">{{ $user->name }}</h2><p class="mt-2 text-sm text-indigo-100">{{ $user->bio_text ?: 'Biodata singkat belum diisi.' }}</p></div><div class="flex h-24 w-24 items-center justify-center overflow-hidden rounded-2xl bg-gradient-to-br from-emerald-400 to-sky-400 text-2xl font-black">@if($user->photo_path)<img src="{{ $user->photoUrl() }}" alt="{{ $user->name }}" class="h-full w-full object-cover">@else{{ strtoupper(mb_substr($user->name ?: 'U',0,1)) }}@endif</div></div></section>
                <section class="grid gap-3 sm:grid-cols-5">@foreach([['Kegiatan',$stats['reports']],['Leads',$stats['leads']],['Closing',$stats['closing']],['Hari aktif',$stats['active_days']],['Skor',$score]] as [$label,$value])<article class="rounded-2xl border border-white/10 bg-[#35385f] p-4"><span class="text-xs text-indigo-200">{{ $label }}</span><strong class="mt-2 block text-2xl">{{ number_format($value,0,',','.') }}</strong></article>@endforeach</section>
                <section id="pencapaian" class="rounded-2xl border border-white/10 bg-[#35385f] p-5"><h2 class="mb-3 text-base font-bold">Badge dan Achievement</h2><div class="flex flex-wrap gap-2">@foreach($badges as $badge)<span class="rounded-full px-3 py-1 text-xs font-semibold {{ $badge['ok'] ? 'bg-emerald-400/20 text-emerald-200' : 'bg-white/10 text-indigo-200' }}">{{ $badge['ok'] ? '✓' : '○' }} {{ $badge['name'] }}</span>@endforeach</div></section>
                <section id="aktivitas" class="rounded-2xl border border-white/10 bg-[#35385f] p-5"><h2 class="mb-3 text-base font-bold">Aktivitas Terbaru</h2><div class="space-y-2">@forelse($reports as $report)<a href="{{ route('reports.show',$report) }}" class="block rounded-xl border border-white/10 p-3 hover:bg-white/10"><div class="flex justify-between gap-3"><strong class="text-sm">{{ $report->title ?: $report->campaign_name }}</strong><span class="text-xs text-indigo-200">{{ optional($report->report_date)->format('d/m/Y') }}</span></div><p class="text-xs text-indigo-200">{{ $report->report_type }} · {{ $report->status }} · {{ $report->leads_count }} leads · {{ $report->closing_count }} closing</p></a>@empty<p class="text-sm text-indigo-200">Belum ada aktivitas.</p>@endforelse</div></section>
                <section id="pengaturan" class="rounded-2xl border border-white/10 bg-[#35385f] p-5"><h2 class="text-base font-bold">Pengaturan Profil</h2><form class="mt-4 grid gap-3" method="POST" action="{{ route('profile.update') }}" enctype="multipart/form-data">@csrf<textarea name="bio_text" maxlength="800" rows="4" class="rounded-lg border-white/10 bg-[#212446] text-white" placeholder="Biodata singkat">{{ old('bio_text', $user->bio_text) }}</textarea><input type="file" name="profile_photo" accept="image/jpeg,image/png,image/webp" class="text-sm text-indigo-100"><button class="w-fit rounded-lg bg-emerald-500 px-4 py-2 text-sm font-bold text-white">Simpan Profil</button></form></section>
            </div>
        </div>
    </div>
</x-layouts.app>
