<?php

return [
    'indicators' => [
        'reg' => [
            'label' => 'Reg',
            'group' => 'Hasil PMB',
            'default_weight' => 10,
            'metric_key' => 'registrasi_personal',
        ],
        'herreg' => [
            'label' => 'Herreg',
            'group' => 'Hasil PMB',
            'default_weight' => 15,
            'metric_key' => 'herregistrasi_personal',
        ],
        'reg_kampus' => [
            'label' => 'Reg Kampus',
            'group' => 'Hasil Kampus',
            'default_weight' => 8,
            'metric_key' => 'registrasi_kampus',
        ],
        'herreg_kampus' => [
            'label' => 'Herreg Kampus',
            'group' => 'Hasil Kampus',
            'default_weight' => 12,
            'metric_key' => 'herregistrasi_kampus',
        ],
        'cpm_cpl' => [
            'label' => 'CPM/CPL',
            'group' => 'Iklan',
            'default_weight' => 12,
            'metric_key' => 'cpm_cpl',
            'default_target' => 4000,
            'direction' => 'lower',
            'step' => '0.01',
        ],
        'closing_iklan' => [
            'label' => 'Closing Iklan',
            'group' => 'Iklan',
            'default_weight' => 8,
            'metric_key' => 'closing_iklan',
            'default_target' => 1,
        ],
        'fu' => [
            'label' => 'FU',
            'group' => 'Aktivitas',
            'default_weight' => 10,
            'metric_key' => 'follow_up_total',
        ],
        'aktivitas_lain' => [
            'label' => 'Aktivitas Lain',
            'group' => 'Aktivitas',
            'default_weight' => 5,
            'metric_key' => 'aktivitas_lain_total',
        ],
        'aktif' => [
            'label' => 'Aktif',
            'group' => 'Aktivitas',
            'default_weight' => 0,
            'metric_key' => 'hari_aktif',
        ],
        'absen' => [
            'label' => 'Absen Tepat Waktu ≤09.00',
            'group' => 'Aktivitas',
            'default_weight' => 1,
            'default_target' => 25,
            'score_by_default' => true,
            'metric_key' => 'absen_masuk',
        ],
        'konten_instagram' => [
            'label' => 'Konten Instagram',
            'group' => 'Digital',
            'default_weight' => 1,
            'default_target' => 25,
            'score_by_default' => true,
            'metric_key' => 'konten_instagram',
        ],
        'konten_facebook' => [
            'label' => 'Konten Facebook',
            'group' => 'Digital',
            'default_weight' => 1,
            'default_target' => 25,
            'score_by_default' => true,
            'metric_key' => 'konten_facebook',
        ],
        'konten_tiktok' => [
            'label' => 'Konten TikTok',
            'group' => 'Digital',
            'default_weight' => 1,
            'default_target' => 25,
            'score_by_default' => true,
            'metric_key' => 'konten_tiktok',
        ],
        'story_instagram' => [
            'label' => 'Story Instagram',
            'group' => 'Digital',
            'default_weight' => 1,
            'default_target' => 25,
            'score_by_default' => true,
            'metric_key' => 'story_instagram',
        ],
        'share_fb' => [
            'label' => 'Share FB',
            'group' => 'Digital',
            'default_weight' => 4,
            'metric_key' => 'share_fb_group',
        ],
        'live_stream' => [
            'label' => 'Live Stream',
            'group' => 'Digital',
            'default_weight' => 6,
            'metric_key' => 'live_streaming',
        ],
        'aff_mhs' => [
            'label' => 'Aff. Mhs',
            'group' => 'Afiliasi',
            'default_weight' => 3,
            'metric_key' => 'affiliator_mahasiswa',
        ],
        'aff_non_mhs' => [
            'label' => 'Aff. Non Mhs',
            'group' => 'Afiliasi',
            'default_weight' => 2,
            'metric_key' => 'affiliator_non_mahasiswa',
        ],
    ],
];
