<?php
namespace App\Http\Controllers;
use App\Models\RsmCoordinatorSchedule;
use App\Models\RsmUser;
use App\Support\AreaRegionals;
use App\Support\RsmRole;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\HttpFoundation\StreamedResponse;
class CoordinatorScheduleController extends Controller
{
    private array $profiles=['Regional 4'=>['name'=>'Hamaruddin','home'=>'Makassar'],'Regional 5'=>['name'=>'Kundi Harto','home'=>'Semarang'],'Regional 6'=>['name'=>'M. Nor Abidin','home'=>'Surabaya'],'Regional 7'=>['name'=>'Nugroho Budi Santoso','home'=>'Banyuwangi']];
    public function index(Request $request) { $user=$request->user(); abort_unless(RsmRole::canViewJadwalKoordinator($user),403); $area=$user->area ?: 'Regional'; $month=preg_match('/^\d{4}-\d{2}$/',(string)$request->query('month'))?$request->query('month'):now()->format('Y-m'); $q=RsmCoordinatorSchedule::query()->where('area',$area)->whereBetween('schedule_date',[$month.'-01',date('Y-m-t',strtotime($month.'-01'))]); if($user->role==='koordinator'&&$user->regional)$q->where('wilayah',$user->regional); foreach(['wilayah','koordinator_name','status'] as $filter) if($request->filled($filter)) $q->where($filter,$request->query($filter)); $rows=$q->orderBy('schedule_date')->orderBy('wilayah')->get(); return view('coordinator-schedule.index',['rows'=>$rows,'month'=>$month,'area'=>$area,'regionals'=>AreaRegionals::forArea($area),'profiles'=>$this->profiles,'canManage'=>RsmRole::canManageCoordinatorSchedule($user)]); }
    public function store(Request $request) { $user=$request->user(); abort_unless(RsmRole::canManageCoordinatorSchedule($user),403); $data=$request->validate(['schedule_date'=>'required|date','wilayah'=>'required|string|max:80','koordinator_name'=>'required|string|max:160','unit_name'=>'required|string|max:200','visit_type'=>['required',Rule::in(['Fisik','Zoom','Telepon'])],'status'=>['required',Rule::in(['Rencana','Dijadwalkan','Selesai','Reschedule'])],'agenda'=>'required|string|max:500','result_text'=>'nullable|string|max:2000','next_action'=>'nullable|string|max:2000']); if($user->role==='koordinator'&&$user->regional!==$data['wilayah'])abort(422,'Koordinator hanya bisa mengatur regionalnya sendiri.'); $profile=$this->profiles[$data['wilayah']]??['name'=>$data['koordinator_name'],'home'=>'']; $kor=RsmUser::where('name',$data['koordinator_name'])->where('regional',$data['wilayah'])->first(); RsmCoordinatorSchedule::updateOrCreate(['area'=>$user->area?:'Regional','schedule_date'=>$data['schedule_date'],'wilayah'=>$data['wilayah'],'unit_name'=>$data['unit_name'],'koordinator_name'=>$data['koordinator_name']],['koordinator_user_id'=>$kor?->id,'koordinator_home'=>$profile['home'],'visit_type'=>$data['visit_type'],'status'=>$data['status'],'agenda'=>$data['agenda'],'result_text'=>$data['result_text']??null,'next_action'=>$data['next_action']??null,'created_by_user_id'=>$user->id,'created_by_name'=>$user->name]); return back()->with('status','Jadwal berhasil disimpan.'); }
    public function update(Request $request,RsmCoordinatorSchedule $schedule) { $user=$request->user(); abort_unless(RsmRole::canManageCoordinatorSchedule($user),403); $this->scope($schedule,$user); $data=$request->validate(['unit_name'=>'required|string|max:200','visit_type'=>['required',Rule::in(['Fisik','Zoom','Telepon'])],'status'=>['required',Rule::in(['Rencana','Dijadwalkan','Selesai','Reschedule'])],'agenda'=>'required|string|max:500','result_text'=>'nullable|string|max:2000','next_action'=>'nullable|string|max:2000','checklist'=>'nullable|array','checklist.*'=>'nullable|string|max:160','attachment'=>'nullable|file|mimes:jpg,jpeg,png,webp,pdf|max:5120']); $data['checklist_json']=json_encode(array_values($data['checklist']??[]),JSON_UNESCAPED_UNICODE); unset($data['checklist']); if($request->hasFile('attachment')) { if($schedule->attachment_path) Storage::disk('public')->delete($schedule->attachment_path); $data['attachment_path']=$request->file('attachment')->store('coordinator-schedules','public'); } $schedule->update($data); return back()->with('status','Jadwal berhasil diperbarui.'); }
    public function attachment(Request $request,RsmCoordinatorSchedule $schedule): StreamedResponse { $this->scope($schedule,$request->user()); abort_unless($schedule->attachment_path && Storage::disk('public')->exists($schedule->attachment_path),404); return Storage::disk('public')->download($schedule->attachment_path); }
    public function destroy(Request $request,RsmCoordinatorSchedule $schedule) { $user=$request->user(); abort_unless(RsmRole::canManageCoordinatorSchedule($user)&&$user->role!=='koordinator',403); $this->scope($schedule,$user); $schedule->delete(); return back()->with('status','Jadwal berhasil dihapus.'); }
    private function scope($schedule,$user):void { abort_unless($schedule->area===($user->area?:'Regional')&&($user->role!=='koordinator'||$schedule->wilayah===$user->regional),404); }
}
